# Dockerfile
FROM python:3.8-buster

ENV PYTHONBUFFERED=1

WORKDIR /kreeckacademy

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt


COPY .env .env

COPY . .

#Start the Django server without running migrations during build
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]