FROM python:3.8-buster

ENV PYTHONBUFFERED=1

WORKDIR /kreeckacademy

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

# Run migrations before starting the server
RUN python manage.py migrate

# Run makemigrations before starting the server
RUN python manage.py makemigrations

CMD python manage.py runserver 0.0.0.0:8000
