services:
  app:
    build: 
      context: .
      dockerfile: DockerFile
    image: kreeckdocker/kreeck-academy:v1.0  # Specify the Docker Hub image and tag
    volumes:
      - .:/kreeckacademy
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - kreeck_network

  compiler:
    build:
      context: .
      dockerfile: dockerfile.compiler
    image: kreeckdocker/kreeck-academy:v1.
    volumes:
      - compiler_user_code:/home/compiler/user_code
    ports:
      - "8001:8001"
    networks:
      - kreeck_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    image: kreeckdocker/kreeck-academy:v1.
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kreeck_network

networks:
  kreeck_network:
    driver: bridge

volumes:
  compiler_user_code: