FROM python:3.8-buster

ENV PYTHONBUFFERED=1

WORKDIR /kreeckacademy

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

# Combine migrations into a single layer to save space and avoid repeated steps
RUN python manage.py makemigrations && python manage.py migrate

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
