version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/kreeckacademy
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*,localhost,127.0.0.1,nginx,app
    networks:
      - kreeck_network

  compiler:
    build:
      context: .
      dockerfile: Dockerfile.compiler
    volumes:
      - compiler_user_code:/home/compiler/user_code
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*,localhost,127.0.0.1,nginx,app
    networks:
      - kreeck_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kreeck_network

networks:
  kreeck_network:
    driver: bridge

volumes:
  compiler_user_code:
