version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/kreeckacademy
    ports:
      - 8000:8000
    image: app:kreeckacademy
    container_name: kreeckacademy_container
    command: python manage.py runserver 0.0.0.0:8000
    