version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/kreeckacademy
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - kreeck_network

  compiler:
    build:
      context: .
      dockerfile: Dockerfile.compiler
    volumes:
      - compiler_user_code:/home/compiler/user_code
    ports:
      - "8001:8001"
    networks:
      - kreeck_network

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONF: ${NGINX_CONF}  # Use environment variable for nginx configuration
    ports:
      - "80:80"
    volumes:
      - ./nginx/SECURITY_CERTIFICATES/kreeck_com/certificate.crt:/etc/nginx/SECURITY_CERTIFICATES/kreeck_com/certificate.crt
      - ./nginx/SECURITY_CERTIFICATES/kreeck_com/kreeck_com.key:/etc/nginx/SECURITY_CERTIFICATES/kreeck_com/kreeck_com.key
    networks:
      - kreeck_network

networks:
  kreeck_network:
    driver: bridge

volumes:
  compiler_user_code:
