version: '3.8'

services:
  app_production:
    image: your_app_image
    container_name: app_production
    ports:
      - "8000:8000"
    networks:
      - kreeck_network

  app_pre_production:
    image: your_app_image
    container_name: app_pre_production
    ports:
      - "8001:8000"
    networks:
      - kreeck_network

  app_development:
    image: your_app_image
    container_name: app_development
    ports:
      - "8002:8000"
    networks:
      - kreeck_network

  compiler:
    build:
      context: .
      dockerfile: Dockerfile.compiler
    volumes:
      - compiler_user_code:/home/compiler/user_code
    ports:
      - "8003:8001"
    networks:
      - kreeck_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TARGET_ENV: development  # Change this value as needed (e.g., production, pre_production)
    depends_on:
      - app_production
      - app_pre_production
      - app_development
      - compiler
    networks:
      - kreeck_network

networks:
  kreeck_network:
    driver: bridge

volumes:
  compiler_user_code:
