FROM python:3.8-buster

ENV PYTHONBUFFERED=1

# Create a user and set permissions
RUN groupadd -r compiler && useradd -r -g compiler compiler
WORKDIR /usr/src/compiler
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .

# Change ownership and permissions
RUN chown -R compiler:compiler /usr/src/compiler
USER compiler

CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
