# Generated by Django 4.2.5 on 2024-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackerthon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrole",
            name="hackerthon",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="user",
        ),
        migrations.AddField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[
                    ("Participant", "Participant"),
                    ("Master", "Master"),
                    ("Project Manager", "Project Manager"),
                ],
                default="Participent",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="UploadVideo",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
