# Generated by Django 4.2.5 on 2024-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_semester_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                max_length=10,
            ),
        ),
    ]
